### ISSUE TITLE
import no.ace.Git results in failure

### ISSUE THREAD

**Issue by frealmyr** [evry-ace/jenkins-ace-library#23]
```
GitHub has been notified of this commit’s build result


org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:

file:/var/jenkins_home/jobs/github%20evry-bergen/jobs/belron/branches/am-mazecluster.hod8ek/builds/3/libs/ace/src/no/ace/Git.groovy: 22: unable to resolve class Matcher 

 @ line 22, column 13.

       Matcher m = env.BRANCH_NAME =~ /^release\/(v[0-9]+\.[0-9]+\.[0-9]+)/

               ^


1 error


	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)

	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)

	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)

	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)

	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)

	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)

	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)

	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)

	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:133)

	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:126)

	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)

	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)

	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:320)

	at hudson.model.ResourceController.execute(ResourceController.java:97)

	at hudson.model.Executor.run(Executor.java:429)

Finished: FAILURE
```

**Comment by ekarlso** [comment]
Not valid.
